# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: http://www.0sta.com
url: http://www.0sta.com
date_format: "ordinal"
title: 零星-0sta
author: 0sta 
paginate: 9

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /atom.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: redcarpet
redcarpet: 
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
pygments: true
permalink: /:year/:month/:day/:title
gems:
    - jekyll-sitemap
collections:
    blog:
        output: true
        permalink: /blog/:path/

# ---------------- #
#      Comments    #
# ---------------- #
duoshuo_short_name: 0sta

# ---------------- #
#      Adsense     #
# ---------------- #
adsense: true
amazon: false
