# Site settings
title: 向珍儿大人致敬
email: tolezai@163.com
description: "七月七日晴，玫瑰尚未凋零，趁此良辰美景，以话语之零星，向珍儿致敬。"
baseurl: ""
url: "http://www.0sta.com"
twitter_username: charlesfuture
github_username:  charlesfuture

# Build settings
markdown: kramdown
permalink: pretty
